add leader endpoints
informatyzacja/recruitment-system pull request #13
Opened 2022-09-14 18:18 UTC by DocentSzachista

2022-09-18 16:57 UTC, Mario-659 requested changes
Fix it 🥺

2022-09-18 16:57 UTC, Mario-659 commented on backend/recruitment-system/src/main/kotlin/pl/edu/pwr/samorzad/informatyzacja/recruitmentsystem/controller/Leaders.kt
> +class Leaders(private val leaderService: LeaderService) {
- change name of the class to LeaderController,
- add `/api/v1` to RequestMapping
- maybe add logger even if not used
- sort and remove unused imports (everywhere)
- add new line at end of file (everywhere)

2022-09-18 16:57 UTC, Mario-659 commented on backend/recruitment-system/src/main/kotlin/pl/edu/pwr/samorzad/informatyzacja/recruitmentsystem/services/LeaderService.kt
> +
- it should be in package service not services

2022-09-18 16:57 UTC, Mario-659 commented on backend/recruitment-system/src/main/kotlin/pl/edu/pwr/samorzad/informatyzacja/recruitmentsystem/repository/LeaderRepository.kt
> +    fun findByIdAndLedTeamId(leaderId: Int, ledTeamId: Int): Leader?
typo in findByIdAnd**Led**TeamId

2022-09-18 17:01 UTC, Mario-659 commented on backend/recruitment-system/src/main/kotlin/pl/edu/pwr/samorzad/informatyzacja/recruitmentsystem/services/LeaderService.kt
> +
add ids to exception messages

2022-09-18 18:14 UTC, Mendrejk requested changes
Fix It!

2022-09-18 18:14 UTC, Mendrejk commented on backend/recruitment-system/src/main/kotlin/pl/edu/pwr/samorzad/informatyzacja/recruitmentsystem/service/LeaderService.kt
> +class LeaderService(var db: LeaderRepository) {
change to val, change name - it's a repository not a database

2022-09-18 18:14 UTC, Mendrejk commented on backend/recruitment-system/src/main/kotlin/pl/edu/pwr/samorzad/informatyzacja/recruitmentsystem/service/LeaderService.kt
> +            ?: throw NoSuchElementException("Leader $teamId not found")
check if team exists and throw NoSuchElementException with a different message

2022-09-18 18:14 UTC, Mendrejk commented on backend/recruitment-system/src/main/kotlin/pl/edu/pwr/samorzad/informatyzacja/recruitmentsystem/service/LeaderService.kt
> +            }
check if team exists and throw NoSuchElementException with a different message

2022-09-18 18:14 UTC, Mendrejk commented on backend/recruitment-system/src/main/resources/application.properties
> +#spring.jpa.properties.hibernate.format_sql=true
Add newline

2022-09-18 18:14 UTC, Mendrejk commented on backend/recruitment-system/src/main/kotlin/pl/edu/pwr/samorzad/informatyzacja/recruitmentsystem/controller/Leaders.kt
> +    private val logger = LoggerFactory.getLogger(this.javaClass)
Add newline after logger

2022-09-21 15:08 UTC, Mendrejk commented on backend/recruitment-system/src/main/kotlin/pl/edu/pwr/samorzad/informatyzacja/recruitmentsystem/controller/Leaders.kt
> +class Leaders(private val leaderService: LeaderService) {
@DocentSzachista you did not change the class name

2022-09-21 17:22 UTC, DocentSzachista commented on backend/recruitment-system/src/main/kotlin/pl/edu/pwr/samorzad/informatyzacja/recruitmentsystem/controller/Leaders.kt
> +class Leaders(private val leaderService: LeaderService) {
Done

2022-09-21 20:59 UTC, Mario-659 requested changes

2022-09-21 20:59 UTC, Mario-659 commented on backend/recruitment-system/src/main/resources/application.properties
> +#spring.jpa.properties.hibernate.format_sql=true
You didn't add newline

2022-09-21 20:59 UTC, Mario-659 commented on backend/recruitment-system/src/main/kotlin/pl/edu/pwr/samorzad/informatyzacja/recruitmentsystem/service/LeaderService.kt
> +
I can see you are throwing an exception when list is empty. Are you sure about that? Shouldn't we just return empty list?

2022-09-22 06:50 UTC, Mario-659 submitted a review, later dismissed

2022-09-22 08:51 UTC, Mendrejk requested changes
Fix It!

2022-09-22 08:51 UTC, Mendrejk commented on backend/recruitment-system/src/main/kotlin/pl/edu/pwr/samorzad/informatyzacja/recruitmentsystem/controller/Leader.kt
> +class Leader(private val leaderService: LeaderService) {
The class (and the file) should be called LeaderController

2022-09-22 08:51 UTC, Mendrejk commented on backend/recruitment-system/src/main/kotlin/pl/edu/pwr/samorzad/informatyzacja/recruitmentsystem/controller/Leader.kt
> +    @GetMapping("/{team_id}/{leader_id}")
The full endpoint should be
/api/v1/**teams**/{team_id}/**leaders**/{leader_id}
Yours is
/api/v1/leaders/{team_id}/{leader_id}

2022-09-22 08:51 UTC, Mendrejk commented on backend/recruitment-system/src/main/kotlin/pl/edu/pwr/samorzad/informatyzacja/recruitmentsystem/controller/Leader.kt
> +    @GetMapping("/{team_id}")
The full endpoint should be
/api/v1/**teams**/{team_id}/**leaders**
Yours is
/api/v1/leaders/{team_id}

2022-09-22 12:43 UTC, Mendrejk approved these changes
Ship It!

2022-09-22 14:30 UTC, Mario-659 approved these changes

2022-09-22 19:06 UTC, deamacto approved these changes

2022-09-22 21:32 UTC, merged