SR-23 Add MakeQuestion component
informatyzacja/recruitment-system pull request #15
Opened 2022-09-17 07:23 UTC by Mario-659

2022-09-17 08:47 UTC, Mendrejk requested changes
Fix It!

2022-09-17 08:47 UTC, Mendrejk commented on frontend/recruitment-system/src/components/Button.js
> +                className="w-96 py-2 px-10 bg-blue hover:bg-dark-blue rounded-lg uppercase">
Those styles get us a squircle-shaped button but the buttons in the mockups are pill-shaped. You can accomplish this with the rounded-full Tailwind class

2022-09-17 08:47 UTC, Mendrejk commented on frontend/recruitment-system/src/index.css
> +  font-family: -apple-system, BlinkMacSystemFont, 'Lato', 'Segoe UI', 'Roboto', 'Oxygen',
Just a question, how did you handle adding the Lato font without including it via google fonts URI? That's how Natalia did it. On yesterday's weekly we discussed  whether we can somehow not use the URI directly as it could break. But I guess you've found a solution.

2022-09-17 08:47 UTC, Mendrejk commented on frontend/recruitment-system/tailwind.config.js
> +        '2btn-width': "1060px"
I see you've added some responsiveness which is nice. But it's still not ideal - on a phone screen vertically, the components don't fit and overflow from the screen.

2022-09-17 08:47 UTC, Mendrejk commented on frontend/recruitment-system/tailwind.config.js
> +      'light-gray': '#ebebeb',
We'll need to discuss the colors, probably on the next, now **semi**weekly meeting. It's fine for now since I guess you used the ones from the mockup, but they don't conform 100% with the "Księgia Identyfikacji Wizualnej". Also, I'm not sure how much do we have to conform to those colors.

2022-09-17 08:55 UTC, Mario-659 commented
@deamacto I know that you are working on Button component too. If you make some changes my MakeQuestion component should still work and look properly so don't worry about it

2022-09-17 08:58 UTC, Mendrejk commented on frontend/recruitment-system/tailwind.config.js
> +        '2btn-width': "1060px"
Maybe it's not in the scope of MVP - this needs to be discussed further

2022-09-17 09:01 UTC, Mario-659 commented
I can see that labels are little bit off, will fix that

2022-09-17 09:02 UTC, Mendrejk requested changes
Fix It!

2022-09-17 09:02 UTC, Mendrejk commented on frontend/recruitment-system/src/components/MakeQuestion.js
> +                <NumberInput text="poziom trudności"/>
It's not really visible on the mockup, but we should use a ComboBox instead of a TextInput. There are to be 5 options: "Bardzo Łatwy" - "Łatwy" - "Średni" - "Trudny" - "Bardzo Trudny". It should be localised in the future but I think we can just hard-code it for now. It has to translate to numbers 1-5 for the backend, ofc

2022-09-17 09:06 UTC, Mario-659 commented on frontend/recruitment-system/src/index.css
> +  font-family: -apple-system, BlinkMacSystemFont, 'Lato', 'Segoe UI', 'Roboto', 'Oxygen',
Hmmm I just didn't add URI. What was the problem when URI wasn't included? It seems to be working now. 
From netlify preview:
![Zrzut ekranu 2022-09-17 110606](https://user-images.githubusercontent.com/78920002/190849262-e81df4fc-ad45-4e17-b45e-42bbcd508e76.png)

2022-09-17 09:08 UTC, Mario-659 commented on frontend/recruitment-system/src/components/MakeQuestion.js
> +                <NumberInput text="poziom trudności"/>
Ohhh ok. Didn't know that

2022-09-17 09:17 UTC, Mario-659 commented on frontend/recruitment-system/tailwind.config.js
> +        '2btn-width': "1060px"
Yep, it should be **quite** easy fix but I think that taking mobile into consideration will add a lot of additional work in different components or pages (assuming there are some additional components in the scope of mvp, not in current jira)

2022-09-17 09:39 UTC, Mario-659 commented on frontend/recruitment-system/src/index.css
> +  font-family: -apple-system, BlinkMacSystemFont, 'Lato', 'Segoe UI', 'Roboto', 'Oxygen',
[link](https://makandracards.com/makandra/59967-css-how-to-find-out-the-rendered-font-in-chrome) 

From my understanding it looks like *Lato* font is installed on my machine. If someone doesn't have *Lato* it will use *Segoe UI* then *Roboto* and so on.

From @kanapka0 pr (where URI is included) netlify preview:
![image](https://user-images.githubusercontent.com/78920002/190850382-876ad1d1-f66a-4508-bd92-42ec6238fdd9.png)

In that case for now I will use @kanapka0 solution

2022-09-17 16:15 UTC, Mario-659 commented
Added combo box to difficulty input. I know that not separating NumberInput and ComboBoxInput might be controversial but component looks the same so maybe this is fine (let me know). I named this new component *SmallInput* - it is very bad, I know. Give some suggestion how to rename it if we don't want to separate these components

2022-09-17 17:21 UTC, Mendrejk requested changes
Fix It!

2022-09-17 17:21 UTC, Mendrejk commented on frontend/recruitment-system/src/components/SmallInput.js
> +    }
Can we use a ternary to avoid mutation? optionsArr can be const then

2022-09-17 17:21 UTC, Mendrejk commented on frontend/recruitment-system/src/components/SmallInput.js
> +    }
Again, use expression instead of a statement so that input is const. If ternary looks too complicated, then maybe extract this code into another function.

2022-09-17 17:25 UTC, Mendrejk commented
> 

I'm not sure how to feel about this, since we are basically creating a different component based on the presence or absence of some props parameter (options). This might be fine behind the curtains, but maybe we should not be creating actual components that way.
Or maybe we could compose this like so: there is a, say, LabeledHorizontalInput component which has another component - either a TextInput or a ComboBoxInput inside. Then we can create two preset components and just use them - some LabeledHorizontalTextInput and LabeledHorizontalComboBoxInput? Actually those names are too long, but something along those lines sounds sensible to me.

2022-09-17 17:48 UTC, Mario-659 commented
My main concern was the styling - I didn't want to break DRY. Right now we are styling mostly in component. Maybe it would be better to add specific classNames in components (like btn-primary) and separate all of the styling to the index.css? Something like this:
```css
.btn-primary {
  @apply text-gray;
  ...
}
```
Then we wouldn't need so many components

2022-09-17 19:41 UTC, Mario-659 commented
Separated most of css into *index.css*. Let me know what you think about this solution 😏

2022-09-18 11:14 UTC, Mendrejk commented
> Separated most of css into _index.css_. Let me know what you think about this solution smirk

CSS looks fine to me, I wouldn't worry about DRY that much, but if you feel like it would be better with component classes, then feel free to change it. I have a concern about those hardcoded px values in the tailwind.config.js file but I'm not sure what should be done about them

2022-09-18 12:21 UTC, Mario-659 commented
I agree, especially with hardcoded breaking point value. Right now if you want to change input width breaking point also needs to be changed

2022-09-18 18:03 UTC, DocentSzachista commented on frontend/recruitment-system/src/components/MakeQuestion.js
> +            <Button text="dodaj pytanie"/>
I would add a possibility to parse as argument link to a button.

2022-09-19 16:16 UTC, Mario-659 commented on frontend/recruitment-system/src/components/MakeQuestion.js
> +            <Button text="dodaj pytanie"/>
What do you mean? Add Link from react-router-dom ([link to Link](https://knowbody.github.io/react-router-docs/api/Link.html)) or URL? Would it be optional then? Note that in this PR I'm not introducing any event behaviour (like `onClick`)

2022-09-19 19:35 UTC, Mendrejk approved these changes

2022-09-19 19:39 UTC, Mendrejk commented
We'll have to figure out the colors and the hardcoded widths, but I feel like those changes can be introduced in future pull requests. Namely, the color changes need be discussed during the nearest standup.

2022-09-21 13:51 UTC, Bravo555 approved these changes

2022-09-21 20:56 UTC, DocentSzachista commented on frontend/recruitment-system/src/components/MakeQuestion.js
> +            <Button text="dodaj pytanie"/>
I meant it about some sort of placeholder of `react-router-dom`'s Link or NavLink so it would for the time being move you back to homepage for example. As parameter you would pass URL. Its just a suggestion

2022-09-21 20:56 UTC, DocentSzachista approved these changes

2022-09-21 21:00 UTC, merged