SR-9 Add Recruiter endpoints
informatyzacja/recruitment-system pull request #16
Opened 2022-09-17 16:01 UTC by Mendrejk

Adds all Recruiter endpoints for the MVP. This is a draft, since the tests are still being worked on.

2022-09-19 17:52 UTC, FilipJQ77 submitted a review, later dismissed

2022-09-19 19:13 UTC, Mario-659 requested changes
To fix 👷

2022-09-19 19:13 UTC, Mario-659 commented on backend/recruitment-system/src/test/groovy/pl/edu/pwr/samorzad/informatyzacja/recruitmentsystem/service/RecruiterServiceSpec.groovy
> +    }
Maybe consider using `thrown` in the order of other statements. In that case it should be like this:
```groovy
1 * teamRepository.findTeamById(alreadyBelongingToTeamId) >> teamOne
1 * recruiterRepository.existsByEmailAndTeamsId(existingRecruiter.email, alreadyBelongingToTeamId) >> true
thrown IllegalArgumentException
0 * _
```

2022-09-19 19:51 UTC, Mendrejk commented on backend/recruitment-system/src/test/groovy/pl/edu/pwr/samorzad/informatyzacja/recruitmentsystem/service/RecruiterServiceSpec.groovy
> +        0 * _
Yeah... that's what I meant. I guess strict mocking is not necessary in this test case, or at least, the stories don't suggest it. Your suggestion fits better here. But I think `_` is better than `any()` here.
https://spockframework.org/spock/docs/1.0/interaction_based_testing.html - See Argument Constraints

2022-09-19 19:53 UTC, Mendrejk commented on backend/recruitment-system/src/test/groovy/pl/edu/pwr/samorzad/informatyzacja/recruitmentsystem/service/RecruiterServiceSpec.groovy
> +    }
Does it change anything in the test logic? I don't think it does but I might be mistaken. For me, just stating that the exception is thrown and separating it from the Mocks looks more readable here.

2022-09-19 20:23 UTC, Mario-659 commented on backend/recruitment-system/src/test/groovy/pl/edu/pwr/samorzad/informatyzacja/recruitmentsystem/service/RecruiterServiceSpec.groovy
> +    }
No, it seems to not make any difference in test logic. You are right about readability

2022-09-19 20:36 UTC, Mario-659 requested changes
> Yeah... that's what I meant. I guess strict mocking is not necessary in this test case, or at least, the stories don't suggest it. Your suggestion fits better here. But I think `_` is better than `any()` here. https://spockframework.org/spock/docs/1.0/interaction_based_testing.html - See Argument Constraints

You are right about `_`. Check your tests because there are still some `0 * _` statements

2022-09-20 07:25 UTC, Mendrejk commented
> 

That's true, I've changed all but one `0 * _` to specific method call checks. I feel like the one in the last test makes sense as otherwise I would need to check at least 2 methods for 0 calls (save & delete). I've changed the user story to better signify that no changes should be made.

2022-09-20 14:52 UTC, Mario-659 commented
Ohh okay, so with `0 * _` test will fail if any method from any mocked object is called (not including methods specified earlier in then block)? I didn't find this statement anywhere. Keep in mind that you can also narrow this down to one object like this:
```groovy
0 * mockedObj._
```

2022-09-20 15:02 UTC, Mendrejk commented
> Ohh okay, so with `0 * _` test will fail if any method from any mocked object is called (not including methods specified earlier in then block)? I didn't find this statement anywhere. Keep in mind that you can also narrow this down to one object like this:
> ```groovy
> 0 * mockedObj._
> ```

Yup, it works exactly as you described.
See https://spockframework.org/spock/docs/1.0/interaction_based_testing.html - Strict Mocking

2022-09-20 15:48 UTC, Bravo555 approved these changes

2022-09-20 17:33 UTC, deamacto approved these changes

2022-09-20 17:39 UTC, merged