SR-11 Add security
informatyzacja/recruitment-system pull request #19
Opened 2022-09-25 14:50 UTC by Mario-659

2022-09-25 16:29 UTC, Mario-659 commented
I just realized that it exposes API for any kind of valid google token, will fix that

2022-09-30 21:23 UTC, Mario-659 commented
Ignore my previous diagrams. From the technical standpoint my implementation is far from perfect but it works as intended.

It works as follows:
- bearer token is missing, invalid, expired -> returns 401 (*SecurityConfiguration.kt:21*)
- bearer token is valid but does not match our client id (was obtained from different app) -> returns 401 (*GoogleJwtFilter:52*)
- email not in recruiters or leaders -> returns 403 (*GoogleJwtFilter:59*)

2022-10-02 14:46 UTC, Bravo555 commented on backend/recruitment-system/src/main/kotlin/pl/edu/pwr/samorzad/informatyzacja/recruitmentsystem/security/SecurityConfiguration.kt
> +            .and()
This `and()` looks kinda redundant, is it necessary?

2022-10-02 15:19 UTC, Mario-659 commented on backend/recruitment-system/src/main/kotlin/pl/edu/pwr/samorzad/informatyzacja/recruitmentsystem/security/SecurityConfiguration.kt
> +            .and()
Yes, it is

2022-10-02 16:47 UTC, Bravo555 approved these changes

2022-10-03 11:32 UTC, Mendrejk requested changes
Fix It!

2022-10-03 11:32 UTC, Mendrejk commented on backend/recruitment-system/src/main/kotlin/pl/edu/pwr/samorzad/informatyzacja/recruitmentsystem/security/GoogleJwtFilter.kt
> +        }
Can we maybe use the elvis operator after .verify() with a code block instead?

2022-10-03 11:32 UTC, Mendrejk commented on backend/recruitment-system/src/main/kotlin/pl/edu/pwr/samorzad/informatyzacja/recruitmentsystem/security/SecurityConfiguration.kt
> +            .and()
So is this .and() redundant? Since you did not remove it

2022-10-03 11:49 UTC, Mario-659 commented on backend/recruitment-system/src/main/kotlin/pl/edu/pwr/samorzad/informatyzacja/recruitmentsystem/security/SecurityConfiguration.kt
> +            .and()
It is not redundant. `and()` does something more than joining statements. When I remove one of them in here it won't compile

2022-10-03 12:03 UTC, Mario-659 commented on backend/recruitment-system/src/main/kotlin/pl/edu/pwr/samorzad/informatyzacja/recruitmentsystem/security/GoogleJwtFilter.kt
> +        }
I think with elvis we can only assign value if something is null (I can't use `return` from elvis statement). Also it will be less readable as there is already one if statement later.

2022-10-03 12:17 UTC, Mendrejk approved these changes
Ship It!

2022-10-03 12:19 UTC, Bravo555 approved these changes

2022-10-03 12:21 UTC, merged