SR-48 Connect QuestionList to backend
informatyzacja/recruitment-system pull request #33
Opened 2022-10-11 20:13 UTC by Mendrejk

2022-10-13 17:48 UTC, Mario-659 requested changes
When I click on Question List page from preview I'm getting redirected to Login (and can't get out of there)

2022-10-13 18:37 UTC, Mendrejk commented
Yes, because the specific netlify url is not added to our API token. I don't know if there is a good way to do this. @Bravo555 ?

2022-10-13 20:27 UTC, Mario-659 commented
Ok, now I can see what is happening so that's fine. Maybe move QuestionList to pages (like Login.jsx)?

2022-10-14 09:12 UTC, Mario-659 approved these changes

2022-10-15 22:07 UTC, deamacto approved these changes

2022-10-17 21:20 UTC, merged